name: Release
   
on: 
  workflow_dispatch:
    inputs:
      newTag: 
        type: string
        required: true
        description: New version
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

permissions: 
  contents: write
env:
  NEW_TAG: ${{ inputs.newTag || github.ref_name }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - run: echo ${{ github.event_name }}

    - name: Tag
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        git tag ${{ inputs.newTag }}        
        git push --tags

    - name: Get previous tag
      id: previousTag
      run: |
        name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
        echo "previousTag: $name"
        echo "previousTag=$name" >> $GITHUB_ENV

    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        fromTag: ${{env.NEW_TAG}}
        toTag: ${{ env.previousTag }}
        writeToFile: false
        includeInvalidCommits: true

    - name: Create Release
      uses: ncipollo/release-action@v1.20.0
      with:
        allowUpdates: true
        draft: false
        makeLatest: true
        tag: ${{env.NEW_TAG}}
        name: ${{env.NEW_TAG}}
        body: ${{ steps.changelog.outputs.changes }}
        token: ${{ secrets.GITHUB_TOKEN }} 
        artifacts: "LICENSE,README.md,retro.css,retro.js" 